//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TonLibDotNet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SampleValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TonLibDotNet.SampleValues", typeof(SampleValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQCJTkhd1W2wztkVNp_dsKBpv2SIoUWoIyzI7mQrbSrj_NSh&quot;}.
        /// </summary>
        public static string AccountAddress {
            get {
                return ResourceManager.GetString("AccountAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;actionDns&quot;,&quot;actions&quot;:[{&quot;@type&quot;:&quot;dns.actionDelete&quot;,&quot;name&quot;:&quot;test.ton&quot;,&quot;category&quot;:&quot;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=&quot;},{&quot;@type&quot;:&quot;dns.actionDeleteAll&quot;}]}.
        /// </summary>
        public static string ActionDns {
            get {
                return ResourceManager.GetString("ActionDns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;actionMsg&quot;,&quot;messages&quot;:[{&quot;@type&quot;:&quot;msg.message&quot;,&quot;destination&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;....&quot;},&quot;public_key&quot;:&quot;.....&quot;,&quot;amount&quot;:10000000,&quot;data&quot;:{&quot;@type&quot;:&quot;msg.dataText&quot;,&quot;text&quot;:&quot;???&quot;},&quot;send_mode&quot;:1}],&quot;allow_send_to_uninited&quot;:true}.
        /// </summary>
        public static string ActionMsg {
            get {
                return ResourceManager.GetString("ActionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;actionNoop&quot;}.
        /// </summary>
        public static string ActionNoop {
            get {
                return ResourceManager.GetString("ActionNoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;adnlAddress&quot;,&quot;adnl_address&quot;:&quot;xfupfrvndwrx7ryltn2zmrgqlwmcdcv2zuhifqgachk3a4xsvi2c4qh&quot;}.
        /// </summary>
        public static string AdnlAddress {
            get {
                return ResourceManager.GetString("AdnlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;bip39Hints&quot;,&quot;words&quot;:[&quot;auction&quot;,&quot;audit&quot;,&quot;august&quot;,&quot;aunt&quot;,&quot;author&quot;,&quot;auto&quot;,&quot;autumn&quot;]}.
        /// </summary>
        public static string Bip39Hints {
            get {
                return ResourceManager.GetString("Bip39Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;blocks.getMasterchainInfo&quot;}.
        /// </summary>
        public static string Blocks_GetMasterchainInfo {
            get {
                return ResourceManager.GetString("Blocks_GetMasterchainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;blocks.masterchainInfo&quot;,
        ///  &quot;last&quot;:{&quot;@type&quot;:&quot;ton.blockIdExt&quot;,
        ///          &quot;workchain&quot;:-1,
        ///          &quot;shard&quot;:&quot;-9223372036854775808&quot;,
        ///          &quot;seqno&quot;:26984517,
        ///          &quot;root_hash&quot;:&quot;k1nEMD+7m+DZAEyktBfy99GTAl/YvFVRBgw3tXr5Xt8=&quot;,
        ///          &quot;file_hash&quot;:&quot;BKPbMdegxyBMEdeWTNY0RG4SI8Cw7tlqCOQkahlj0cM=&quot;},
        ///  &quot;state_root_hash&quot;:&quot;/K7jV7AXp/MKqBL/+3XWpU3kFYp2ObdDG+b9minKUn8=&quot;,
        ///  &quot;init&quot;:{&quot;@type&quot;:&quot;ton.blockIdExt&quot;,
        ///          &quot;workchain&quot;:-1,
        ///          &quot;shard&quot;:&quot;0&quot;,
        ///          &quot;seqno&quot;:0,
        ///          &quot;root_ha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blocks_MasterchainInfo {
            get {
                return ResourceManager.GetString("Blocks_MasterchainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;changeLocalPassword&quot;,&quot;input_key&quot;:{&quot;@type&quot;:&quot;inputKeyRegular&quot;,&quot;key&quot;:{&quot;@type&quot;:&quot;key&quot;,&quot;public_key&quot;:&quot;Pub...NZz4&quot;,&quot;secret&quot;:&quot;yXO...nA=&quot;},&quot;local_password&quot;:&quot;AQIDBAU=&quot;},&quot;new_local_password&quot;:&quot;BwYF&quot;}.
        /// </summary>
        public static string ChangeLocalPassword {
            get {
                return ResourceManager.GetString("ChangeLocalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;config&quot;,&quot;config&quot;:&quot;test-value&quot;,&quot;blockchain_name&quot;:&quot;test&quot;,&quot;use_callbacks_for_network&quot;:true,&quot;ignore_cache&quot;:true}.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;createNewKey&quot;,&quot;local_password&quot;:&quot;111&quot;,&quot;mnemonic_password&quot;:&quot;222&quot;,&quot;random_extra_seed&quot;:&quot;333&quot;}.
        /// </summary>
        public static string CreateNewKey {
            get {
                return ResourceManager.GetString("CreateNewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;createQuery&quot;,&quot;private_key&quot;:{&quot;@type&quot;:&quot;inputKeyRegular&quot;,&quot;key&quot;:{&quot;@type&quot;:&quot;key&quot;,&quot;public_key&quot;:&quot;PuZ...pU9&quot;,&quot;secret&quot;:&quot;zB...WY=&quot;}},&quot;address&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQA...dT0&quot;},&quot;timeout&quot;:60,&quot;action&quot;:{&quot;@type&quot;:&quot;actionMsg&quot;,&quot;messages&quot;:[{&quot;@type&quot;:&quot;msg.message&quot;,&quot;destination&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQA...dT0&quot;},&quot;amount&quot;:10000000,&quot;data&quot;:{&quot;@type&quot;:&quot;msg.dataText&quot;,&quot;text&quot;:&quot;U2Vu...kVU&quot;},&quot;send_mode&quot;:1}],&quot;allow_send_to_uninited&quot;:true},&quot;initial_account_state&quot;:{&quot;@type&quot;:&quot;wallet.v3.ini [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateQuery {
            get {
                return ResourceManager.GetString("CreateQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;deleteAllKeys&quot;}.
        /// </summary>
        public static string DeleteAllKeys {
            get {
                return ResourceManager.GetString("DeleteAllKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;deleteKey&quot;,&quot;key&quot;:{&quot;@type&quot;:&quot;key&quot;,&quot;public_key&quot;:&quot;Pub...HnG&quot;,&quot;secret&quot;:&quot;gbV...bA=&quot;}}.
        /// </summary>
        public static string DeleteKey {
            get {
                return ResourceManager.GetString("DeleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;dns.actionDelete&quot;,&quot;name&quot;:&quot;test.ton&quot;,&quot;category&quot;:&quot;AAA...AAA=&quot;}.
        /// </summary>
        public static string Dns_ActionDelete {
            get {
                return ResourceManager.GetString("Dns_ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;dns.actionDeleteAll&quot;}.
        /// </summary>
        public static string Dns_ActionDeleteAll {
            get {
                return ResourceManager.GetString("Dns_ActionDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;dns.actionSet&quot;,&quot;entry&quot;:{&quot;@type&quot;:&quot;dns.entry&quot;,&quot;name&quot;:&quot;test2.ton&quot;,&quot;category&quot;:&quot;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=&quot;,&quot;entry&quot;:{&quot;@type&quot;:&quot;dns.entryDataAdnlAddress&quot;,&quot;adnl_address&quot;:{&quot;@type&quot;:&quot;adnlAddress&quot;,&quot;adnl_address&quot;:&quot;xfupfrvndwrx7ryltn2zmrgqlwmcdcv2zuhifqgachk3a4xsvi2c4qh&quot;}}}}.
        /// </summary>
        public static string Dns_ActionSet {
            get {
                return ResourceManager.GetString("Dns_ActionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;dns.entry&quot;,&quot;name&quot;:&quot;toncenter.&quot;,&quot;category&quot;:&quot;GfAkQe5Yj9sm7iSyVo3QNcPJIG4Rq5eb5i5VVYodF/8=&quot;,&quot;entry&quot;:{&quot;@type&quot;:&quot;dns.entryDataNextResolver&quot;,&quot;resolver&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQAiIsvar4OYBn8BGBf9flfin6tl5poBx4MgJe4CQJYasy51&quot;}}}.
        /// </summary>
        public static string Dns_Entry {
            get {
                return ResourceManager.GetString("Dns_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;dns.entryDataAdnlAddress&quot;,&quot;adnl_address&quot;:{&quot;@type&quot;:&quot;adnlAddress&quot;,&quot;adnl_address&quot;:&quot;xfupfrvndwrx7ryltn2zmrgqlwmcdcv2zuhifqgachk3a4xsvi2c4qh&quot;}}.
        /// </summary>
        public static string Dns_EntryDataAdnlAddress {
            get {
                return ResourceManager.GetString("Dns_EntryDataAdnlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;dns.entryDataNextResolver&quot;,&quot;resolver&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQAiIsvar4OYBn8BGBf9flfin6tl5poBx4MgJe4CQJYasy51&quot;}}.
        /// </summary>
        public static string Dns_EntryDataNextResolver {
            get {
                return ResourceManager.GetString("Dns_EntryDataNextResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;dns.entryDataText&quot;,&quot;text&quot;:&quot;Hello, World&quot;}.
        /// </summary>
        public static string Dns_EntryDataText {
            get {
                return ResourceManager.GetString("Dns_EntryDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;dns.initialAccountState&quot;,&quot;public_key&quot;:&quot;PuboprBeKvVkQVnCcT7lt3WkNMaHL9F4OM9oxnWOgQ-ZB9Nm&quot;,&quot;wallet_id&quot;:698983191}.
        /// </summary>
        public static string Dns_InitialAccountState {
            get {
                return ResourceManager.GetString("Dns_InitialAccountState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;dns.resolve&quot;,&quot;name&quot;:&quot;toncenter.&quot;,&quot;account_address&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQC3dNlesgVD8YbAazcauIrXBPfiVhMMr5YYk2in0Mtsz0Bz&quot;},&quot;category&quot;:&quot;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=&quot;,&quot;ttl&quot;:777}.
        /// </summary>
        public static string Dns_Resolve {
            get {
                return ResourceManager.GetString("Dns_Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;dns.resolved&quot;,&quot;entries&quot;:[{&quot;@type&quot;:&quot;dns.entry&quot;,&quot;name&quot;:&quot;toncenter.&quot;,&quot;category&quot;:&quot;GfAkQe5Yj9sm7iSyVo3QNcPJIG4Rq5eb5i5VVYodF/8=&quot;,&quot;entry&quot;:{&quot;@type&quot;:&quot;dns.entryDataNextResolver&quot;,&quot;resolver&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQAiIsvar4OYBn8BGBf9flfin6tl5poBx4MgJe4CQJYasy51&quot;}}}]}.
        /// </summary>
        public static string Dns_Resolved {
            get {
                return ResourceManager.GetString("Dns_Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;error&quot;,&quot;code&quot;:400,&quot;message&quot;:&quot;INVALID_ACCOUNT_ADDRESSFailed to parse account address&quot;}.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;exportedEncryptedKey&quot;,&quot;data&quot;:&quot;iMX/cKz...zpg==&quot;}.
        /// </summary>
        public static string ExportedEncryptedKey {
            get {
                return ResourceManager.GetString("ExportedEncryptedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;exportedKey&quot;,&quot;word_list&quot;:[&quot;gasp&quot;,&quot;shine&quot;,&quot;patient&quot;,&quot;poverty&quot;,&quot;oak&quot;,&quot;leaf&quot;,&quot;actor&quot;,&quot;shift&quot;,&quot;festival&quot;,&quot;route&quot;,&quot;six&quot;,&quot;track&quot;,&quot;same&quot;,&quot;home&quot;,&quot;derive&quot;,&quot;ready&quot;,&quot;table&quot;,&quot;eye&quot;,&quot;card&quot;,&quot;praise&quot;,&quot;affair&quot;,&quot;when&quot;,&quot;ship&quot;,&quot;trim&quot;]}.
        /// </summary>
        public static string ExportedKey {
            get {
                return ResourceManager.GetString("ExportedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;exportedPemKey&quot;,&quot;pem&quot;:&quot;-----BEGIN ENCRYPTED PRIVATE KEY-----\nMIGbMFcG...WE71Nf4=\n-----END ENCRYPTED PRIVATE KEY-----\n&quot;}.
        /// </summary>
        public static string ExportedPemKey {
            get {
                return ResourceManager.GetString("ExportedPemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;exportedUnencryptedKey&quot;,&quot;data&quot;:&quot;Vn9nPsOY7YZ3iNnpV5Opsk7oY1eDclOkm5ht0N0XtrE=&quot;}.
        /// </summary>
        public static string ExportedUnencryptedKey {
            get {
                return ResourceManager.GetString("ExportedUnencryptedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;exportEncryptedKey&quot;,&quot;input_key&quot;:{&quot;@type&quot;:&quot;inputKeyRegular&quot;,&quot;key&quot;:{&quot;@type&quot;:&quot;key&quot;,&quot;public_key&quot;:&quot;PuY...EIP&quot;,&quot;secret&quot;:&quot;B6Y...rg=&quot;},&quot;local_password&quot;:&quot;AQIDBAU=&quot;},&quot;key_password&quot;:&quot;FQMHCw==&quot;}.
        /// </summary>
        public static string ExportEncryptedKey {
            get {
                return ResourceManager.GetString("ExportEncryptedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;exportKey&quot;,&quot;input_key&quot;:{&quot;@type&quot;:&quot;inputKeyRegular&quot;,&quot;key&quot;:{&quot;@type&quot;:&quot;key&quot;,&quot;public_key&quot;:&quot;PuY...CQ&quot;,&quot;secret&quot;:&quot;K5F..I=&quot;},&quot;local_password&quot;:&quot;PQ...Q=&quot;}}.
        /// </summary>
        public static string ExportKey {
            get {
                return ResourceManager.GetString("ExportKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;exportPemKey&quot;,&quot;input_key&quot;:{&quot;@type&quot;:&quot;inputKeyRegular&quot;,&quot;key&quot;:{&quot;@type&quot;:&quot;key&quot;,&quot;public_key&quot;:&quot;PuZ...aLD&quot;,&quot;secret&quot;:&quot;Qe6...bc=&quot;},&quot;local_password&quot;:&quot;AQIDBAU=&quot;},&quot;key_password&quot;:&quot;FQMHCw==&quot;}.
        /// </summary>
        public static string ExportPemKey {
            get {
                return ResourceManager.GetString("ExportPemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;exportUnencryptedKey&quot;,&quot;input_key&quot;:{&quot;@type&quot;:&quot;inputKeyRegular&quot;,&quot;key&quot;:{&quot;@type&quot;:&quot;key&quot;,&quot;public_key&quot;:&quot;PuYJ...gEIP&quot;,&quot;secret&quot;:&quot;B6Ya...Aorg=&quot;},&quot;local_password&quot;:&quot;AQIDBAU=&quot;}}.
        /// </summary>
        public static string ExportUnencryptedKey {
            get {
                return ResourceManager.GetString("ExportUnencryptedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;fees&quot;,&quot;in_fwd_fee&quot;:2048000,&quot;storage_fee&quot;:1575,&quot;gas_fee&quot;:2994000,&quot;fwd_fee&quot;:1228000}.
        /// </summary>
        public static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;fullAccountState&quot;,&quot;address&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQCJTkhd1W2wztkVNp_dsKBpv2SIoUWoIyzI7mQrbSrj_NSh&quot;},&quot;balance&quot;:&quot;136217239329079&quot;,&quot;last_transaction_id&quot;:{&quot;@type&quot;:&quot;internal.transactionId&quot;,&quot;lt&quot;:&quot;34942442000005&quot;,&quot;hash&quot;:&quot;vhl79O/OZ4LCC7cdkKj22uNv5diIrIltOLujpFOLwTk=&quot;},&quot;block_id&quot;:{&quot;@type&quot;:&quot;ton.blockIdExt&quot;,&quot;workchain&quot;:-1,&quot;shard&quot;:&quot;-9223372036854775808&quot;,&quot;seqno&quot;:27011756,&quot;root_hash&quot;:&quot;AhS55h8lmOyxtw29gWux0XZzXgiAbE69UsP44xIWdXM=&quot;,&quot;file_hash&quot;:&quot;TwDj86Fbvgvxte2UXpYtm2CpMSC/wIyxZph6mPDn99A=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FullAccountState {
            get {
                return ResourceManager.GetString("FullAccountState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;getAccountAddress&quot;,&quot;initial_account_state&quot;:{&quot;@type&quot;:&quot;wallet.v3.initialAccountState&quot;,&quot;public_key&quot;:&quot;PuZ....mpU9&quot;,&quot;wallet_id&quot;:698983191},&quot;revision&quot;:3,&quot;workchain_id&quot;:-1}.
        /// </summary>
        public static string GetAccountAddress {
            get {
                return ResourceManager.GetString("GetAccountAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;getAccountState&quot;,&quot;account_address&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQCJTkhd1W2wztkVNp_dsKBpv2SIoUWoIyzI7mQrbSrj_NSh&quot;}}.
        /// </summary>
        public static string GetAccountState {
            get {
                return ResourceManager.GetString("GetAccountState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;getBip39Hints&quot;,&quot;prefix&quot;:&quot;au&quot;}.
        /// </summary>
        public static string GetBip39Hints {
            get {
                return ResourceManager.GetString("GetBip39Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;importEncryptedKey&quot;,&quot;exported_encrypted_key&quot;:{&quot;@type&quot;:&quot;exportedEncryptedKey&quot;,&quot;data&quot;:&quot;sAtI...YOYg=&quot;},&quot;local_password&quot;:&quot;AQIDBAU=&quot;,&quot;key_password&quot;:&quot;FQMHCw==&quot;}.
        /// </summary>
        public static string ImportEncryptedKey {
            get {
                return ResourceManager.GetString("ImportEncryptedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;importKey&quot;,&quot;exported_key&quot;:{&quot;@type&quot;:&quot;exportedKey&quot;,&quot;word_list&quot;:[&quot;fabric&quot;,&quot;draw&quot;,&quot;forward&quot;,&quot;olive&quot;,&quot;lamp&quot;,&quot;purpose&quot;,&quot;sight&quot;,&quot;loan&quot;,&quot;elevator&quot;,&quot;diet&quot;,&quot;clutch&quot;,&quot;fit&quot;,&quot;eagle&quot;,&quot;useless&quot;,&quot;tiger&quot;,&quot;useless&quot;,&quot;veteran&quot;,&quot;night&quot;,&quot;curtain&quot;,&quot;spend&quot;,&quot;crack&quot;,&quot;intact&quot;,&quot;resource&quot;,&quot;orbit&quot;]},&quot;local_password&quot;:&quot;MTIz&quot;,&quot;mnemonic_password&quot;:&quot;NDU2&quot;}.
        /// </summary>
        public static string ImportKey {
            get {
                return ResourceManager.GetString("ImportKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;importPemKey&quot;,&quot;exported_key&quot;:{&quot;@type&quot;:&quot;exportedPemKey&quot;,&quot;pem&quot;:&quot;-----BEGIN ENCRYPTED PRIVATE KEY-----\nMI...lJU=\n-----END ENCRYPTED PRIVATE KEY-----\n&quot;},&quot;local_password&quot;:&quot;AQIDBAU=&quot;,&quot;key_password&quot;:&quot;FQMHCw==&quot;}.
        /// </summary>
        public static string ImportPemKey {
            get {
                return ResourceManager.GetString("ImportPemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;importUnencryptedKey&quot;,&quot;exported_unencrypted_key&quot;:{&quot;@type&quot;:&quot;exportedUnencryptedKey&quot;,&quot;data&quot;:&quot;Zdb...YM=&quot;},&quot;local_password&quot;:&quot;AQIDBAU=&quot;}.
        /// </summary>
        public static string ImportUnencryptedKey {
            get {
                return ResourceManager.GetString("ImportUnencryptedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;init&quot;,&quot;options&quot;:{&quot;@type&quot;:&quot;options&quot;,&quot;config&quot;:{&quot;@type&quot;:&quot;config&quot;,&quot;config&quot;:&quot;test-value&quot;,&quot;blockchain_name&quot;:&quot;test&quot;,&quot;use_callbacks_for_network&quot;:true,&quot;ignore_cache&quot;:true},&quot;keystore_type&quot;:{&quot;@type&quot;:&quot;keyStoreTypeDirectory&quot;,&quot;directory&quot;:&quot;D:/Temp/&quot;}}}.
        /// </summary>
        public static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;inputKeyFake&quot;}.
        /// </summary>
        public static string InputKey_Fake {
            get {
                return ResourceManager.GetString("InputKey_Fake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;inputKeyRegular&quot;,&quot;key&quot;:{&quot;@type&quot;:&quot;key&quot;,&quot;public_key&quot;:&quot;PuY...qoCQ&quot;,&quot;secret&quot;:&quot;K5F...JhgI=&quot;},&quot;local_password&quot;:&quot;PQ...Q=&quot;}.
        /// </summary>
        public static string InputKey_Regular {
            get {
                return ResourceManager.GetString("InputKey_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;internal.transactionId&quot;,&quot;lt&quot;:&quot;34942442000005&quot;,&quot;hash&quot;:&quot;vhl79O/OZ4LCC7cdkKj22uNv5diIrIltOLujpFOLwTk=&quot;}.
        /// </summary>
        public static string Internal_TransactionId {
            get {
                return ResourceManager.GetString("Internal_TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;key&quot;,&quot;public_key&quot;:&quot;Pua...ywkQ&quot;,&quot;secret&quot;:&quot;gSu4...WTnQe0=&quot;}.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;liteServer.getInfo&quot;}.
        /// </summary>
        public static string LiteServer_GetInfo {
            get {
                return ResourceManager.GetString("LiteServer_GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;liteServer.info&quot;,&quot;now&quot;:1675246773,&quot;version&quot;:257,&quot;capabilities&quot;:&quot;7&quot;}.
        /// </summary>
        public static string LiteServer_Info {
            get {
                return ResourceManager.GetString("LiteServer_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;msg.dataRaw&quot;,&quot;body&quot;:&quot;te6cckEBAQEAAgAAAEysuc0=&quot;,&quot;init_state&quot;:&quot;???&quot;}.
        /// </summary>
        public static string Msg_DataRaw {
            get {
                return ResourceManager.GetString("Msg_DataRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;msg.dataText&quot;,&quot;text&quot;:&quot;Um95YWx0eQ==&quot;}.
        /// </summary>
        public static string Msg_DataText {
            get {
                return ResourceManager.GetString("Msg_DataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;msg.message&quot;,&quot;destination&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQAk...mdT0&quot;},&quot;public_key&quot;:&quot;PuZi...pU9&quot;,&quot;amount&quot;:10000000,&quot;data&quot;:{&quot;@type&quot;:&quot;msg.dataText&quot;,&quot;text&quot;:&quot;U2VudCB1c2luZyBodHRwczovL2dpdGh1Yi5jb20vanVzdGRtaXRyeS9Ub25MaWIuTkVU&quot;},&quot;send_mode&quot;:1}.
        /// </summary>
        public static string Msg_Message {
            get {
                return ResourceManager.GetString("Msg_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;ok&quot;}.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;options.info&quot;,&quot;config_info&quot;:{&quot;@type&quot;:&quot;options.configInfo&quot;,&quot;default_wallet_id&quot;:&quot;698983191&quot;,&quot;default_rwallet_init_public_key&quot;:&quot;Puasxr0QfFZZnYISRphVse7XHKfW7pZU5SJarVHXvQ+rpzkD&quot;}}.
        /// </summary>
        public static string Options_Info {
            get {
                return ResourceManager.GetString("Options_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;packAccountAddress&quot;,&quot;account_address&quot;:{&quot;@type&quot;:&quot;unpackedAccountAddress&quot;,&quot;workchain_id&quot;:0,&quot;bounceable&quot;:true,&quot;testnet&quot;:false,&quot;addr&quot;:&quot;iU5IXdVtsM7ZFTaf3bCgab9kiKFFqCMsyO5kK20q4/w=&quot;}}.
        /// </summary>
        public static string PackAccountAddress {
            get {
                return ResourceManager.GetString("PackAccountAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;query.estimateFees&quot;,&quot;id&quot;:1,&quot;ignore_chksig&quot;:true}.
        /// </summary>
        public static string Query_EstimateFees {
            get {
                return ResourceManager.GetString("Query_EstimateFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;query.fees&quot;,&quot;source_fees&quot;:{&quot;@type&quot;:&quot;fees&quot;,&quot;in_fwd_fee&quot;:2048000,&quot;storage_fee&quot;:1575,&quot;gas_fee&quot;:2994000,&quot;fwd_fee&quot;:1228000},&quot;destination_fees&quot;:[{&quot;@type&quot;:&quot;fees&quot;,&quot;in_fwd_fee&quot;:0,&quot;storage_fee&quot;:1575,&quot;gas_fee&quot;:100000,&quot;fwd_fee&quot;:0}]}.
        /// </summary>
        public static string Query_Fees {
            get {
                return ResourceManager.GetString("Query_Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;query.forget&quot;,&quot;id&quot;:1}.
        /// </summary>
        public static string Query_Forget {
            get {
                return ResourceManager.GetString("Query_Forget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;query.getInfo&quot;,&quot;id&quot;:1}.
        /// </summary>
        public static string Query_GetInfo {
            get {
                return ResourceManager.GetString("Query_GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;query.info&quot;,&quot;id&quot;:1,&quot;valid_until&quot;:1678173619,&quot;body_hash&quot;:&quot;XWY...NdE=&quot;,&quot;body&quot;:&quot;te6...BL1U=&quot;,&quot;init_state&quot;:&quot;???&quot;}.
        /// </summary>
        public static string Query_Info {
            get {
                return ResourceManager.GetString("Query_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;query.send&quot;,&quot;id&quot;:1}.
        /// </summary>
        public static string Query_Send {
            get {
                return ResourceManager.GetString("Query_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;raw.accountState&quot;,&quot;code&quot;:&quot;te6...zJw==&quot;,&quot;data&quot;:&quot;te6...CWaB&quot;,&quot;frozen_hash&quot;:&quot;???&quot;}.
        /// </summary>
        public static string Raw_AccountState {
            get {
                return ResourceManager.GetString("Raw_AccountState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;raw.fullAccountState&quot;,&quot;balance&quot;:&quot;136219372128177&quot;,&quot;code&quot;:&quot;te6cckEBAQEAcQAA3v8AIN0gggFMl7ohggEznLqxn3Gw7UTQ0x/THzHXC//jBOCk8mCDCNcYINMf0x/TH/gjE7vyY+1E0NMf0x/T/9FRMrryoVFEuvKiBPkBVBBV+RDyo/gAkyDXSpbTB9QC+wDo0QGkyMsfyx/L/8ntVBC9ba0=&quot;,&quot;data&quot;:&quot;te6cckEBAQEAKgAAUAAAACMpqaMXb7DhKt9TV4heY445fd1j4cnc24PkHSaiiBxRdV3sZK6FBhF3&quot;,&quot;last_transaction_id&quot;:{&quot;@type&quot;:&quot;internal.transactionId&quot;,&quot;lt&quot;:&quot;34948872000007&quot;,&quot;hash&quot;:&quot;j2fRsAIg2Abex+P+GCRu9dNcmGs36Wd9U0gedEGX8oA=&quot;},&quot;block_id&quot;:{&quot;@type&quot;:&quot;ton.blockIdExt&quot;,&quot;workchain&quot;:-1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Raw_FullAccountState {
            get {
                return ResourceManager.GetString("Raw_FullAccountState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;raw.getAccountState&quot;,&quot;account_address&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQCJTkhd1W2wztkVNp_dsKBpv2SIoUWoIyzI7mQrbSrj_NSh&quot;}}.
        /// </summary>
        public static string Raw_GetAccountState {
            get {
                return ResourceManager.GetString("Raw_GetAccountState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;raw.getTransactions&quot;,&quot;account_address&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQCJTkhd1W2wztkVNp_dsKBpv2SIoUWoIyzI7mQrbSrj_NSh&quot;},&quot;from_transaction_id&quot;:{&quot;@type&quot;:&quot;internal.transactionId&quot;,&quot;lt&quot;:34948872000007,&quot;hash&quot;:&quot;j2fRsAIg2Abex\u002BP\u002BGCRu9dNcmGs36Wd9U0gedEGX8oA=&quot;}}.
        /// </summary>
        public static string Raw_GetTransactions {
            get {
                return ResourceManager.GetString("Raw_GetTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;raw.message&quot;,&quot;source&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQAyAAlbgteBHCuI50EzuVvu9Zrk4Ts7pKU3bsphGBcyY0O_&quot;},&quot;destination&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQCJTkhd1W2wztkVNp_dsKBpv2SIoUWoIyzI7mQrbSrj_NSh&quot;},&quot;value&quot;:&quot;880000000&quot;,&quot;fwd_fee&quot;:&quot;666672&quot;,&quot;ihr_fee&quot;:&quot;1&quot;,&quot;created_lt&quot;:&quot;34948872000005&quot;,&quot;body_hash&quot;:&quot;lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=&quot;,&quot;msg_data&quot;:{&quot;@type&quot;:&quot;msg.dataRaw&quot;,&quot;body&quot;:&quot;te6cckEBAQEAAgAAAEysuc0=&quot;,&quot;init_state&quot;:&quot;12345&quot;}}.
        /// </summary>
        public static string Raw_Message {
            get {
                return ResourceManager.GetString("Raw_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;raw.transaction&quot;,&quot;utime&quot;:1675263677,&quot;data&quot;:&quot;te6cC9u5d6&quot;,&quot;transaction_id&quot;:{&quot;@type&quot;:&quot;internal.transactionId&quot;,&quot;lt&quot;:&quot;34948872000007&quot;,&quot;hash&quot;:&quot;j2fRsAIg2Abex+P+GCRu9dNcmGs36Wd9U0gedEGX8oA=&quot;},&quot;fee&quot;:&quot;12&quot;,&quot;storage_fee&quot;:&quot;13&quot;,&quot;other_fee&quot;:&quot;15&quot;,&quot;in_msg&quot;:{&quot;@type&quot;:&quot;raw.message&quot;,&quot;source&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQAyAAlbgteBHCuI50EzuVvu9Zrk4Ts7pKU3bsphGBcyY0O_&quot;},&quot;destination&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQCJTkhd1W2wztkVNp_dsKBpv2SIoUWoIyzI7mQrbSrj_NSh&quot;},&quot;value&quot;:&quot;0&quot;,&quot;fwd_fee&quot;:&quot;6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Raw_Transaction {
            get {
                return ResourceManager.GetString("Raw_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;raw.transactions&quot;,&quot;transactions&quot;:[{&quot;@type&quot;:&quot;raw.transaction&quot;,&quot;utime&quot;:1675263677,&quot;data&quot;:&quot;abcdef&quot;,&quot;transaction_id&quot;:{&quot;@type&quot;:&quot;internal.transactionId&quot;,&quot;lt&quot;:&quot;34948872000007&quot;,&quot;hash&quot;:&quot;j2fRsAIg2Abex+P+GCRu9dNcmGs36Wd9U0gedEGX8oA=&quot;},&quot;fee&quot;:&quot;0&quot;,&quot;storage_fee&quot;:&quot;0&quot;,&quot;other_fee&quot;:&quot;0&quot;,&quot;in_msg&quot;:{&quot;@type&quot;:&quot;raw.message&quot;,&quot;source&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQAyAAlbgteBHCuI50EzuVvu9Zrk4Ts7pKU3bsphGBcyY0O_&quot;},&quot;destination&quot;:{&quot;@type&quot;:&quot;accountAddress&quot;,&quot;account_address&quot;:&quot;EQCJTkhd1W2wztkVNp_dsKBpv2SIoUWoIyzI7m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Raw_Transactions {
            get {
                return ResourceManager.GetString("Raw_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;sync&quot;}.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;ton.blockIdExt&quot;,
        ///          &quot;workchain&quot;:-1,
        ///          &quot;shard&quot;:&quot;-9223372036854775808&quot;,
        ///          &quot;seqno&quot;:26984517,
        ///          &quot;root_hash&quot;:&quot;k1nEMD+7m+DZAEyktBfy99GTAl/YvFVRBgw3tXr5Xt8=&quot;,
        ///          &quot;file_hash&quot;:&quot;BKPbMdegxyBMEdeWTNY0RG4SI8Cw7tlqCOQkahlj0cM=&quot;}.
        /// </summary>
        public static string Ton_BlockIdEx {
            get {
                return ResourceManager.GetString("Ton_BlockIdEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;uninited.accountState&quot;,&quot;frozen_hash&quot;:&quot;---&quot;}.
        /// </summary>
        public static string Uninited_AccountState {
            get {
                return ResourceManager.GetString("Uninited_AccountState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;unpackAccountAddress&quot;,&quot;account_address&quot;:&quot;EQCJTkhd1W2wztkVNp_dsKBpv2SIoUWoIyzI7mQrbSrj_NSh&quot;}.
        /// </summary>
        public static string UnpackAccountAddress {
            get {
                return ResourceManager.GetString("UnpackAccountAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;unpackedAccountAddress&quot;,&quot;workchain_id&quot;:0,&quot;bounceable&quot;:true,&quot;testnet&quot;:false,&quot;addr&quot;:&quot;iU5IXdVtsM7ZFTaf3bCgab9kiKFFqCMsyO5kK20q4/w=&quot;}.
        /// </summary>
        public static string UnpackedAccountAddress {
            get {
                return ResourceManager.GetString("UnpackedAccountAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;updateSyncState&quot;,&quot;sync_state&quot;:{&quot;@type&quot;:&quot;syncStateInProgress&quot;,&quot;from_seqno&quot;:27005885,&quot;to_seqno&quot;:27011756,&quot;current_seqno&quot;:27011750}}.
        /// </summary>
        public static string UpdateSyncState {
            get {
                return ResourceManager.GetString("UpdateSyncState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;wallet.highload.v1.initialAccountState&quot;,&quot;public_key&quot;:&quot;PuZi0henKVaHtfaaRZs-DedaOxKUlWkS_jBE1qYLQ4m9mpU9&quot;,&quot;wallet_id&quot;:4085333890}.
        /// </summary>
        public static string Wallet_HighloadV1InitialAccountState {
            get {
                return ResourceManager.GetString("Wallet_HighloadV1InitialAccountState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;wallet.highload.v2.initialAccountState&quot;,&quot;public_key&quot;:&quot;PuZi0henKVaHtfaaRZs-DedaOxKUlWkS_jBE1qYLQ4m9mpU9&quot;,&quot;wallet_id&quot;:4085333890}.
        /// </summary>
        public static string Wallet_HighloadV2InitialAccountState {
            get {
                return ResourceManager.GetString("Wallet_HighloadV2InitialAccountState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;wallet.v3.accountState&quot;,&quot;wallet_id&quot;:&quot;698983191&quot;,&quot;seqno&quot;:35}.
        /// </summary>
        public static string Wallet_V3AccountState {
            get {
                return ResourceManager.GetString("Wallet_V3AccountState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@type&quot;:&quot;wallet.v3.initialAccountState&quot;,&quot;public_key&quot;:&quot;PuZi0henKVaHtfaaRZs-DedaOxKUlWkS_jBE1qYLQ4m9mpU9&quot;,&quot;wallet_id&quot;:4085333890}.
        /// </summary>
        public static string Wallet_V3InitialAccountState {
            get {
                return ResourceManager.GetString("Wallet_V3InitialAccountState", resourceCulture);
            }
        }
    }
}
